[gcp_service_account]
type = "service_account"
project_id = "calendario-man-462414"
private_key_id = "XXX"
private_key = "-----BEGIN PRIVATE KEY-----\\nMIIE...\\n-----END PRIVATE KEY-----\\n"
client_email = "streamlit-editor@calendario-man-462414.iam.gserviceaccount.com"
token_uri = "https://oauth2.googleapis.com/token"
