[gcp_service_account]
type = "service_account"
project_id = "calendario-man-462414"
private_key_id = "c843a1755d48e3ee263084c9c696c23c39aa35d6"
private_key = "-----BEGIN PRIVATE KEY-----\\nMIIEvgIBADANBgkqhkiG9w0B...\\n-----END PRIVATE KEY-----\\n"
client_email = "streamlit-editor@calendario-man-462414.iam.gserviceaccount.com"
client_id = "104961127736283474680"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-editor%40calendario-man-462414.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
